In [1]:
# pip install basketball-reference-web-scraper

In [2]:
from basketball_reference_web_scraper import client
from basketball_reference_web_scraper.data import Team
import pandas as pd
import numpy as np

## **Season Totals Raw** - Very Useful

In [44]:
raw_totals_2018 = client.players_season_totals(2018)

In [46]:
# raw_totals_2018

In [4]:
df_raw_totals_2018 = pd.DataFrame(raw_totals_2018)
df_raw_totals_2018.head(10)

,slug,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,...,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points
0,abrinal01,√Ålex Abrines,[Position.SHOOTING_GUARD],24,Team.OKLAHOMA_CITY_THUNDER,75,8,1134,115,291,...,39,46,26,88,28,38,8,25,124,353
1,acyqu01,Quincy Acy,[Position.POWER_FORWARD],27,Team.BROOKLYN_NETS,70,8,1359,130,365,...,49,60,40,217,57,33,29,60,149,411
2,adamsst01,Steven Adams,[Position.CENTER],24,Team.OKLAHOMA_CITY_THUNDER,76,76,2487,448,712,...,160,286,384,301,88,92,78,128,215,1056
3,adebaba01,Bam Adebayo,[Position.CENTER],20,Team.MIAMI_HEAT,69,19,1368,174,340,...,129,179,118,263,101,32,41,66,138,477
4,afflaar01,Arron Afflalo,[Position.SHOOTING_GUARD],32,Team.ORLANDO_MAGIC,53,3,682,65,162,...,22,26,4,62,30,4,9,21,56,179
5,aldrico01,Cole Aldrich,[Position.CENTER],29,Team.MINNESOTA_TIMBERWOLVES,21,0,49,5,15,...,2,6,3,12,3,2,1,1,11,12
6,aldrila01,LaMarcus Aldridge,[Position.CENTER],32,Team.SAN_ANTONIO_SPURS,75,75,2509,687,1347,...,334,399,246,389,152,43,90,111,161,1735
7,allenja01,Jarrett Allen,[Position.CENTER],19,Team.BROOKLYN_NETS,72,31,1441,234,397,...,114,147,144,244,49,28,88,82,147,587
8,allenka01,Kadeem Allen,[Position.POINT_GUARD],25,Team.BOSTON_CELTICS,18,1,107,6,22,...,7,9,4,7,12,3,2,9,15,19
9,allento01,Tony Allen,[Position.SMALL_FORWARD],36,Team.NEW_ORLEANS_PELICANS,22,0,273,44,91,...,11,21,20,27,9,11,3,19,49,103

## **Advanced Season Totals** - Pretty Useful

In [5]:
all_season_2019 = client.players_advanced_season_totals(season_end_year=2019)

In [6]:
type(all_season_2019)

list

In [7]:
import pandas as pd

In [8]:
df_2019 = pd.DataFrame(all_season_2019)
df_2019.head()

,slug,name,positions,age,team,games_played,minutes_played,player_efficiency_rating,true_shooting_percentage,three_point_attempt_rate,...,turnover_percentage,usage_percentage,offensive_win_shares,defensive_win_shares,win_shares,win_shares_per_48_minutes,offensive_box_plus_minus,defensive_box_plus_minus,box_plus_minus,value_over_replacement_player
0,abrinal01,√Ålex Abrines,[Position.SHOOTING_GUARD],25,Team.OKLAHOMA_CITY_THUNDER,31,588,6.3,0.507,0.809,...,7.9,12.2,0.1,0.6,0.6,0.053,-2.4,-0.9,-3.4,-0.2
1,acyqu01,Quincy Acy,[Position.POWER_FORWARD],28,Team.PHOENIX_SUNS,10,123,2.9,0.379,0.833,...,15.2,9.2,-0.1,0.0,-0.1,-0.022,-5.7,-0.3,-5.9,-0.1
2,adamsja01,Jaylen Adams,[Position.POINT_GUARD],22,Team.ATLANTA_HAWKS,34,428,7.6,0.474,0.673,...,19.7,13.5,-0.1,0.2,0.1,0.011,-3.1,-1.3,-4.4,-0.3
3,adamsst01,Steven Adams,[Position.CENTER],25,Team.OKLAHOMA_CITY_THUNDER,80,2669,18.5,0.591,0.002,...,12.6,16.4,5.1,4.0,9.1,0.163,0.6,2.1,2.7,3.2
4,adebaba01,Bam Adebayo,[Position.CENTER],21,Team.MIAMI_HEAT,82,1913,17.9,0.623,0.031,...,17.1,15.8,3.4,3.4,6.8,0.171,-0.6,3.6,3.0,2.4

In [9]:
df_2019.to_csv('advanced_season_totals_2019.csv')

## **Individual Game Play-By-Play** - Not very useful

In [10]:
pbp_20181016 = client.play_by_play(
    home_team=Team.BOSTON_CELTICS,
    year=2018,
    month=10,
    day=16,
)

In [11]:
df_20181016 = pd.DataFrame(pbp_20181016)

In [12]:
df_20181016.head(10)

,period,period_type,remaining_seconds_in_period,relevant_team,away_team,home_team,away_score,home_score,description
0,1,PeriodType.QUARTER,700.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,R. Covington misses 3-pt jump shot from 27 ft
1,1,PeriodType.QUARTER,700.0,Team.BOSTON_CELTICS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,Defensive rebound by Team
2,1,PeriodType.QUARTER,675.0,Team.BOSTON_CELTICS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,J. Tatum misses 3-pt jump shot from 25 ft
3,1,PeriodType.QUARTER,673.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,Defensive rebound by D. ≈†ariƒá
4,1,PeriodType.QUARTER,668.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,Turnover by B. Simmons (bad pass; steal by G. ...
5,1,PeriodType.QUARTER,663.0,Team.BOSTON_CELTICS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,J. Brown misses 2-pt layup from 2 ft
6,1,PeriodType.QUARTER,658.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,0,0,Defensive rebound by B. Simmons
7,1,PeriodType.QUARTER,655.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,2,0,J. Embiid makes 2-pt layup from 1 ft (assist b...
8,1,PeriodType.QUARTER,636.0,Team.BOSTON_CELTICS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,2,0,J. Tatum misses 2-pt layup from 5 ft
9,1,PeriodType.QUARTER,635.0,Team.PHILADELPHIA_76ERS,Team.PHILADELPHIA_76ERS,Team.BOSTON_CELTICS,2,0,Defensive rebound by B. Simmons

## **Box Scores by Player** - Very Useful

In [13]:
westbrook2019 = client.regular_season_player_box_scores(
  player_identifier="westbru01",season_end_year=2019
 
)

In [14]:
df_westbrook2019 = pd.DataFrame(westbrook2019)
df_westbrook2019.head(10)

,date,team,location,opponent,outcome,seconds_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,...,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points_scored,game_score,plus_minus
0,2018-10-21,Team.OKLAHOMA_CITY_THUNDER,Location.HOME,Team.SACRAMENTO_KINGS,Outcome.LOSS,2109,13,23,1,6,...,2,10,8,0,0,5,2,32,22.9,-13
1,2018-10-25,Team.OKLAHOMA_CITY_THUNDER,Location.HOME,Team.BOSTON_CELTICS,Outcome.LOSS,1942,5,20,0,5,...,1,14,8,0,0,5,5,13,3.7,-5
2,2018-10-28,Team.OKLAHOMA_CITY_THUNDER,Location.HOME,Team.PHOENIX_SUNS,Outcome.WIN,1852,8,13,0,0,...,1,8,7,4,0,6,3,23,20.7,8
3,2018-10-30,Team.OKLAHOMA_CITY_THUNDER,Location.HOME,Team.LOS_ANGELES_CLIPPERS,Outcome.WIN,2010,13,25,1,3,...,2,2,8,3,1,3,4,32,25.6,18
4,2018-11-01,Team.OKLAHOMA_CITY_THUNDER,Location.AWAY,Team.CHARLOTTE_HORNETS,Outcome.WIN,2228,12,24,0,3,...,1,7,10,3,0,3,3,29,24.8,3
5,2018-11-02,Team.OKLAHOMA_CITY_THUNDER,Location.AWAY,Team.WASHINGTON_WIZARDS,Outcome.WIN,1560,10,16,0,1,...,0,3,12,4,0,1,1,23,27.3,10
6,2018-11-05,Team.OKLAHOMA_CITY_THUNDER,Location.HOME,Team.NEW_ORLEANS_PELICANS,Outcome.WIN,1511,6,16,0,2,...,0,7,9,1,0,6,3,17,9.2,11
7,2018-11-19,Team.OKLAHOMA_CITY_THUNDER,Location.AWAY,Team.SACRAMENTO_KINGS,Outcome.LOSS,2194,12,25,4,10,...,2,11,7,3,0,4,5,29,22.5,4
8,2018-11-21,Team.OKLAHOMA_CITY_THUNDER,Location.AWAY,Team.GOLDEN_STATE_WARRIORS,Outcome.WIN,1973,5,15,1,5,...,0,11,13,2,1,4,4,11,11.2,25
9,2018-11-23,Team.OKLAHOMA_CITY_THUNDER,Location.HOME,Team.CHARLOTTE_HORNETS,Outcome.WIN,2082,10,18,1,4,...,0,12,8,2,0,4,3,30,26.6,17

## **Script to get Player Box Scores for period between years**

In [15]:
def box_score_df(player_id, year):
  df = pd.DataFrame(client.regular_season_player_box_scores(player_identifier=player_id,
  season_end_year=year))
  return df

def all_box_scores(player_id,year_start,year_stop):
    df = pd.concat([box_score_df(player_id, year) for year in range(year_start,year_stop)],
                   axis = 'rows',
                   join = 'inner')
    return df

In [16]:
import pandas as pd
from basketball_reference_web_scraper.data import Team
from basketball_reference_web_scraper import client

### **Test for Russell Westbrooks box scores between 2014-2018

In [17]:
westbrook_4years = all_box_scores("westbru01",2015,2020)
print(westbrook_4years.head(10))
print(westbrook_4years.tail(10))

         date                        team       location  \
0  2014-10-29  Team.OKLAHOMA_CITY_THUNDER  Location.AWAY
1  2014-10-30  Team.OKLAHOMA_CITY_THUNDER  Location.AWAY
2  2014-11-28  Team.OKLAHOMA_CITY_THUNDER  Location.HOME
3  2014-12-02  Team.OKLAHOMA_CITY_THUNDER  Location.AWAY
4  2014-12-05  Team.OKLAHOMA_CITY_THUNDER  Location.AWAY
5  2014-12-07  Team.OKLAHOMA_CITY_THUNDER  Location.AWAY
6  2014-12-09  Team.OKLAHOMA_CITY_THUNDER  Location.HOME
7  2014-12-11  Team.OKLAHOMA_CITY_THUNDER  Location.HOME
8  2014-12-12  Team.OKLAHOMA_CITY_THUNDER  Location.AWAY
9  2014-12-14  Team.OKLAHOMA_CITY_THUNDER  Location.HOME

                      opponent       outcome  seconds_played  \
0  Team.PORTLAND_TRAIL_BLAZERS  Outcome.LOSS            1959
1    Team.LOS_ANGELES_CLIPPERS  Outcome.LOSS             523
2         Team.NEW_YORK_KNICKS   Outcome.WIN            1428
3    Team.NEW_ORLEANS_PELICANS  Outcome.LOSS            1982
4      Team.PHILADELPHIA_76ERS   Outcome.WIN            1843
5         Team.DETROIT_PISTONS   Outcome.WIN            2080
6         Team.MILWAUKEE_BUCKS   Outcome.WIN            1927
7     Team.CLEVELAND_CAVALIERS   Outcome.WIN            2145
8  Team.MINNESOTA_TIMBERWOLVES   Outcome.WIN            2145
9            Team.PHOENIX_SUNS   Outcome.WIN            1591

   made_field_goals  attempted_field_goals  made_three_point_field_goals  \
0                11                     26                             1
1                 1                      3                             0
2                12                     17                             3
3                 6                     20                             1
4                 8                     14                             1
5                 9                     19                             1
6                 8                     16                             0
7                12                     24                             0
8                12                     19                             2
9                 7                     18                             1

   attempted_three_point_field_goals  ...  offensive_rebounds  \
0                                  2  ...                   2
1                                  1  ...                   0
2                                  4  ...                   4
3                                  4  ...                   1
4                                  3  ...                   0
5                                  3  ...                   1
6                                  2  ...                   2
7                                  2  ...                   1
8                                  3  ...                   1
9                                  4  ...                   4

   defensive_rebounds  assists  steals  blocks  turnovers  personal_fouls  \
0                   1        6       3       0          2               3
1                   0        4       1       0          3               2
2                   3        8       1       0          3               2
3                   5        7       2       0          7               3
4                   5        7       2       0          6               3
5                  10        7       0       0          4               1
6                   3        7       3       0          5               5
7                   6        8       1       0          4               0
8                   5        6       2       0          4               3
9                   4        8       2       0          3               2

   points_scored  game_score  plus_minus
0             38        29.5          -4
1              2         0.3          -3
2             32        30.6          24
3             21         9.9         -16
4             27        20.0          11
5             22        15.3          -9
6             28        22.0          24
7             26        19.1           5
8             34        28.3          16
9             28        26.0          17

[10 rows x 22 columns]
          date                        team       location  \
63  2019-03-22  Team.OKLAHOMA_CITY_THUNDER  Location.AWAY
64  2019-03-25  Team.OKLAHOMA_CITY_THUNDER  Location.AWAY
65  2019-03-27  Team.OKLAHOMA_CITY_THUNDER  Location.HOME
66  2019-03-29  Team.OKLAHOMA_CITY_THUNDER  Location.HOME
67  2019-03-31  Team.OKLAHOMA_CITY_THUNDER  Location.HOME
68  2019-04-02  Team.OKLAHOMA_CITY_THUNDER  Location.HOME
69  2019-04-05  Team.OKLAHOMA_CITY_THUNDER  Location.HOME
70  2019-04-07  Team.OKLAHOMA_CITY_THUNDER  Location.AWAY
71  2019-04-09  Team.OKLAHOMA_CITY_THUNDER  Location.HOME
72  2019-04-10  Team.OKLAHOMA_CITY_THUNDER  Location.AWAY

                       opponent       outcome  seconds_played  \
63         Team.TORONTO_RAPTORS   Outcome.WIN            2206
64       Team.MEMPHIS_GRIZZLIES  Outcome.LOSS            2205
65          Team.INDIANA_PACERS   Outcome.WIN            2211
66          Team.DENVER_NUGGETS  Outcome.LOSS            2139
67        Team.DALLAS_MAVERICKS  Outcome.LOSS            2259
68      Team.LOS_ANGELES_LAKERS   Outcome.WIN            2208
69         Team.DETROIT_PISTONS   Outcome.WIN            2112
70  Team.MINNESOTA_TIMBERWOLVES   Outcome.WIN            2291
71         Team.HOUSTON_ROCKETS   Outcome.WIN            2224
72         Team.MILWAUKEE_BUCKS   Outcome.WIN            2188

    made_field_goals  attempted_field_goals  made_three_point_field_goals  \
63                 6                     20                             2
64                 6                     20                             1
65                 6                     15                             2
66                11                     22                             1
67                 9                     19                             3
68                 8                     23                             2
69                 6                     18                             1
70                10                     22                             2
71                11                     23                             4
72                 7                     10                             1

    attempted_three_point_field_goals  ...  offensive_rebounds  \
63                                  9  ...                   4
64                                  6  ...                   0
65                                  4  ...                   1
66                                  5  ...                   3
67                                  8  ...                   2
68                                  9  ...                   5
69                                  4  ...                   1
70                                  6  ...                   1
71                                 10  ...                   2
72                                  3  ...                   0

    defensive_rebounds  assists  steals  blocks  turnovers  personal_fouls  \
63                   8       13       4       1          3               3
64                   5        7       0       0          1               3
65                  10       12       2       1          2               0
66                   6        9       2       0          3               3
67                   9       11       2       0          3               2
68                  15       21       3       0          2               2
69                   7       15       1       0          4               2
70                   9       15       1       0          4               3
71                  10       10       0       0          3               4
72                  11       17       1       1          4               3

    points_scored  game_score  plus_minus
63             18        20.8          18
64             16         7.4         -20
65             17        21.3           8
66             27        23.6          -1
67             25        25.3          -3
68             20        29.6          24
69             19        16.7           4
70             27        24.5          -1
71             29        24.1           3
72             15        21.7           6

[10 rows x 22 columns]

In [18]:
westbrook_4years.describe()

,seconds_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points_scored,game_score,plus_minus
count,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000,381.000000
mean,2109.653543,9.170604,21.039370,1.582677,5.115486,6.388451,8.094488,1.750656,7.669291,10.110236,1.900262,0.309711,4.669291,2.674541,26.312336,21.551969,4.737533
std,283.312698,3.558500,6.324641,1.508437,3.116560,3.803914,4.216072,1.333093,3.559395,3.636572,1.341847,0.560672,2.162072,1.428694,9.656717,8.572427,12.501974
min,523.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.000000,-36.000000
25%,2015.000000,7.000000,17.000000,0.000000,3.000000,3.000000,5.000000,1.000000,5.000000,7.000000,1.000000,0.000000,3.000000,2.000000,20.000000,16.000000,-4.000000
50%,2159.000000,9.000000,20.000000,1.000000,5.000000,6.000000,8.000000,2.000000,7.000000,10.000000,2.000000,0.000000,4.000000,3.000000,25.000000,21.700000,5.000000
75%,2258.000000,11.000000,25.000000,2.000000,7.000000,9.000000,11.000000,3.000000,10.000000,12.000000,3.000000,1.000000,6.000000,4.000000,32.000000,27.200000,14.000000
max,3128.000000,21.000000,44.000000,8.000000,16.000000,19.000000,22.000000,7.000000,17.000000,24.000000,6.000000,2.000000,11.000000,6.000000,58.000000,45.600000,36.000000

In [19]:
westbrook_4years.to_csv('westbrook_2014_2019.csv')

In [20]:
schedule_2018 = client.season_schedule(season_end_year=2018)

In [21]:
df_schedule_2018 = pd.DataFrame(schedule_2018)
df_schedule_2018.head(10)

,start_time,away_team,home_team,away_team_score,home_team_score
0,2017-10-18 00:01:00+00:00,Team.BOSTON_CELTICS,Team.CLEVELAND_CAVALIERS,99,102
1,2017-10-18 02:30:00+00:00,Team.HOUSTON_ROCKETS,Team.GOLDEN_STATE_WARRIORS,122,121
2,2017-10-18 23:00:00+00:00,Team.CHARLOTTE_HORNETS,Team.DETROIT_PISTONS,90,102
3,2017-10-18 23:00:00+00:00,Team.BROOKLYN_NETS,Team.INDIANA_PACERS,131,140
4,2017-10-18 23:00:00+00:00,Team.MIAMI_HEAT,Team.ORLANDO_MAGIC,109,116
5,2017-10-18 23:00:00+00:00,Team.PHILADELPHIA_76ERS,Team.WASHINGTON_WIZARDS,115,120
6,2017-10-18 23:30:00+00:00,Team.MILWAUKEE_BUCKS,Team.BOSTON_CELTICS,108,100
7,2017-10-19 00:00:00+00:00,Team.NEW_ORLEANS_PELICANS,Team.MEMPHIS_GRIZZLIES,91,103
8,2017-10-19 00:30:00+00:00,Team.ATLANTA_HAWKS,Team.DALLAS_MAVERICKS,117,111
9,2017-10-19 01:00:00+00:00,Team.DENVER_NUGGETS,Team.UTAH_JAZZ,96,106

In [22]:
df_schedule_2018.tail(100)

,start_time,away_team,home_team,away_team_score,home_team_score
1212,2018-04-10 23:00:00+00:00,Team.CHARLOTTE_HORNETS,Team.INDIANA_PACERS,119,93
1213,2018-04-10 23:30:00+00:00,Team.PHILADELPHIA_76ERS,Team.ATLANTA_HAWKS,121,113
1214,2018-04-11 00:00:00+00:00,Team.BOSTON_CELTICS,Team.WASHINGTON_WIZARDS,101,113
1215,2018-04-11 00:30:00+00:00,Team.PHOENIX_SUNS,Team.DALLAS_MAVERICKS,124,97
1216,2018-04-11 01:00:00+00:00,Team.GOLDEN_STATE_WARRIORS,Team.UTAH_JAZZ,79,119
...,...,...,...,...,...
1307,2018-05-29 01:00:00+00:00,Team.GOLDEN_STATE_WARRIORS,Team.HOUSTON_ROCKETS,101,92
1308,2018-06-01 01:00:00+00:00,Team.CLEVELAND_CAVALIERS,Team.GOLDEN_STATE_WARRIORS,114,124
1309,2018-06-04 00:00:00+00:00,Team.CLEVELAND_CAVALIERS,Team.GOLDEN_STATE_WARRIORS,103,122
1310,2018-06-07 01:00:00+00:00,Team.GOLDEN_STATE_WARRIORS,Team.CLEVELAND_CAVALIERS,110,102
1311,2018-06-09 01:00:00+00:00,Team.GOLDEN_STATE_WARRIORS,Team.CLEVELAND_CAVALIERS,108,85

In [23]:
df_2020_schedule = pd.DataFrame(client.season_schedule(season_end_year=2020))

In [24]:
df_schedule_2018.shape

(1312, 5)

In [25]:
df_2020_schedule.shape

(1229, 5)

In [26]:
df_2020_schedule.tail(20)

,start_time,away_team,home_team,away_team_score,home_team_score
1209,2020-04-14 01:00:00+00:00,Team.DALLAS_MAVERICKS,Team.DENVER_NUGGETS,NaN,NaN
1210,2020-04-14 02:30:00+00:00,Team.PORTLAND_TRAIL_BLAZERS,Team.GOLDEN_STATE_WARRIORS,NaN,NaN
1211,2020-04-14 02:30:00+00:00,Team.MINNESOTA_TIMBERWOLVES,Team.LOS_ANGELES_CLIPPERS,NaN,NaN
1212,2020-04-14 23:30:00+00:00,Team.TORONTO_RAPTORS,Team.MIAMI_HEAT,NaN,NaN
1213,2020-04-14 23:30:00+00:00,Team.DETROIT_PISTONS,Team.NEW_YORK_KNICKS,NaN,NaN
1214,2020-04-15 02:00:00+00:00,Team.DENVER_NUGGETS,Team.UTAH_JAZZ,NaN,NaN
1215,2020-04-15 02:30:00+00:00,Team.SACRAMENTO_KINGS,Team.LOS_ANGELES_LAKERS,NaN,NaN
1216,2020-04-15 23:30:00+00:00,Team.CLEVELAND_CAVALIERS,Team.ATLANTA_HAWKS,NaN,NaN
1217,2020-04-15 23:30:00+00:00,Team.CHICAGO_BULLS,Team.BOSTON_CELTICS,NaN,NaN
1218,2020-04-15 23:30:00+00:00,Team.MILWAUKEE_BUCKS,Team.BROOKLYN_NETS,NaN,NaN
1219,2020-04-15 23:30:00+00:00,Team.OKLAHOMA_CITY_THUNDER,Team.DALLAS_MAVERICKS,NaN,NaN
1220,2020-04-15 23:30:00+00:00,Team.MEMPHIS_GRIZZLIES,Team.HOUSTON_ROCKETS,NaN,NaN
1221,2020-04-15 23:30:00+00:00,Team.NEW_YORK_KNICKS,Team.MINNESOTA_TIMBERWOLVES,NaN,NaN
1222,2020-04-15 23:30:00+00:00,Team.TORONTO_RAPTORS,Team.ORLANDO_MAGIC,NaN,NaN
1223,2020-04-15 23:30:00+00:00,Team.CHARLOTTE_HORNETS,Team.PHILADELPHIA_76ERS,NaN,NaN
1224,2020-04-15 23:30:00+00:00,Team.NEW_ORLEANS_PELICANS,Team.SAN_ANTONIO_SPURS,NaN,NaN
1225,2020-04-15 23:30:00+00:00,Team.INDIANA_PACERS,Team.WASHINGTON_WIZARDS,NaN,NaN
1226,2020-04-16 02:00:00+00:00,Team.LOS_ANGELES_LAKERS,Team.PHOENIX_SUNS,NaN,NaN
1227,2020-04-16 02:00:00+00:00,Team.LOS_ANGELES_CLIPPERS,Team.PORTLAND_TRAIL_BLAZERS,NaN,NaN
1228,2020-04-16 02:00:00+00:00,Team.GOLDEN_STATE_WARRIORS,Team.SACRAMENTO_KINGS,NaN,NaN

In [27]:
client.player_box_scores

In [28]:
def allscores(day, month, year):
    df = pd.DataFrame(client.player_box_scores(day=day, month=month, year=year))
    return df

In [48]:
columns = allscores(2,1,2020).columns

for i, j, k  in range(1,32), range(1,12), range(2012,2021):
    date_list = [i,j,k]

In [30]:
client.player_box_scores(15,10,2016)

[]

In [100]:
import datetime
from datetime import date
# date1 = 1,2,3
# date2 = date.today()
start = datetime.datetime(2013, 1, 1)
end = date.today()
mydates = pd.date_range(start, end)#.tolist()

In [32]:
def all_data(y, m, d):
    start = datetime.datetime(y, m, d)
    end = date.today()
    mydates = pd.date_range(start, end)#.tolist()

    for x in mydates:
        day = x.day
        month = x.month
        year = x.year
        allscores(day, month, year)

In [101]:
df = []
for x in mydates:
        day = x.day
        month = x.month
        year = x.year
        df.append(allscores(day, month, year))

In [103]:
joined = pd.DataFrame(columns = columns)

for x in range(len(df)):
    joined = pd.DataFrame.append(joined, df[x], ignore_index=True)

In [94]:
joined = pd.DataFrame.append(df[0], df[1], df,[2])

In [88]:
df[35]

,slug,name,team,location,opponent,outcome,seconds_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,...,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,game_score
0,jokicni01,Nikola Jokiƒá,Team.DENVER_NUGGETS,Location.AWAY,Team.UTAH_JAZZ,Outcome.WIN,2386,14,24,0,...,2,4,6,15,10,2,0,1,2,33.9
1,drumman01,Andre Drummond,Team.DETROIT_PISTONS,Location.HOME,Team.PHOENIX_SUNS,Outcome.WIN,2288,14,19,0,...,3,5,7,12,4,3,0,3,1,33.4
2,youngtr01,Trae Young,Team.ATLANTA_HAWKS,Location.AWAY,Team.MINNESOTA_TIMBERWOLVES,Outcome.WIN,2231,10,23,6,...,12,13,0,4,11,1,0,3,3,31.2
3,lowryky01,Kyle Lowry,Team.TORONTO_RAPTORS,Location.HOME,Team.INDIANA_PACERS,Outcome.WIN,2252,12,21,3,...,5,5,3,5,10,2,0,3,3,30.5
4,porzikr01,Kristaps Porzi≈Üƒ£is,Team.DALLAS_MAVERICKS,Location.HOME,Team.MEMPHIS_GRIZZLIES,Outcome.LOSS,1748,10,20,5,...,7,7,1,11,2,2,1,0,3,28.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,mcgruro01,Rodney McGruder,Team.LOS_ANGELES_CLIPPERS,Location.HOME,Team.MIAMI_HEAT,Outcome.WIN,409,0,3,0,...,0,0,1,0,0,0,0,0,0,-1.4
178,bonejo01,Jordan Bone,Team.DETROIT_PISTONS,Location.HOME,Team.PHOENIX_SUNS,Outcome.WIN,438,0,3,0,...,0,0,0,1,1,0,0,0,1,-1.5
179,jacksju01,Justin Jackson,Team.DALLAS_MAVERICKS,Location.HOME,Team.MEMPHIS_GRIZZLIES,Outcome.LOSS,862,1,8,1,...,0,0,1,0,0,0,0,0,0,-1.5
180,exumda01,Dante Exum,Team.CLEVELAND_CAVALIERS,Location.AWAY,Team.OKLAHOMA_CITY_THUNDER,Outcome.LOSS,892,0,1,0,...,0,0,0,2,2,1,0,4,3,-2.9
181,spellom01,Omari Spellman,Team.GOLDEN_STATE_WARRIORS,Location.AWAY,Team.BROOKLYN_NETS,Outcome.LOSS,1666,0,3,0,...,1,4,0,1,1,0,0,1,2,-3.1

In [105]:
joined.to_csv('2013-2020.csv')

In [106]:
joined

,slug,name,team,location,opponent,outcome,seconds_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,...,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,game_score
0,anthoca01,Carmelo Anthony,Team.NEW_YORK_KNICKS,Location.HOME,Team.PORTLAND_TRAIL_BLAZERS,Outcome.LOSS,2472,14,24,5,...,12,14,2,5,4,1,0,2,3,36.5
1,smithjo03,Josh Smith,Team.ATLANTA_HAWKS,Location.AWAY,Team.NEW_ORLEANS_HORNETS,Outcome.WIN,2234,11,20,1,...,0,0,2,11,7,3,4,1,2,27.0
2,holidjr01,Jrue Holiday,Team.PHILADELPHIA_76ERS,Location.AWAY,Team.LOS_ANGELES_LAKERS,Outcome.WIN,2352,10,19,2,...,4,4,0,2,10,2,0,1,1,24.9
3,smithjr01,J.R. Smith,Team.NEW_YORK_KNICKS,Location.HOME,Team.PORTLAND_TRAIL_BLAZERS,Outcome.LOSS,2413,10,22,4,...,4,6,3,8,5,3,0,2,2,24.0
4,turneev01,Evan Turner,Team.PHILADELPHIA_76ERS,Location.AWAY,Team.LOS_ANGELES_LAKERS,Outcome.WIN,2455,8,14,2,...,4,7,1,12,5,2,1,1,1,23.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200788,mcgruro01,Rodney McGruder,Team.LOS_ANGELES_CLIPPERS,Location.HOME,Team.MIAMI_HEAT,Outcome.WIN,409,0,3,0,...,0,0,1,0,0,0,0,0,0,-1.4
200789,bonejo01,Jordan Bone,Team.DETROIT_PISTONS,Location.HOME,Team.PHOENIX_SUNS,Outcome.WIN,438,0,3,0,...,0,0,0,1,1,0,0,0,1,-1.5
200790,jacksju01,Justin Jackson,Team.DALLAS_MAVERICKS,Location.HOME,Team.MEMPHIS_GRIZZLIES,Outcome.LOSS,862,1,8,1,...,0,0,1,0,0,0,0,0,0,-1.5
200791,exumda01,Dante Exum,Team.CLEVELAND_CAVALIERS,Location.AWAY,Team.OKLAHOMA_CITY_THUNDER,Outcome.LOSS,892,0,1,0,...,0,0,0,2,2,1,0,4,3,-2.9
200792,spellom01,Omari Spellman,Team.GOLDEN_STATE_WARRIORS,Location.AWAY,Team.BROOKLYN_NETS,Outcome.LOSS,1666,0,3,0,...,1,4,0,1,1,0,0,1,2,-3.1

In [148]:
dfs = pd.DataFrame(df[0])

In [152]:
dfs[0][2]

,slug,name,team,location,opponent,outcome,seconds_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,...,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,game_score
0,davisan02,Anthony Davis,Team.LOS_ANGELES_LAKERS,Location.HOME,Team.NEW_ORLEANS_PELICANS,Outcome.WIN,2277,15,21,3,...,13,13,2,11,1,3,1,3,3,42.2
1,hardeja01,James Harden,Team.HOUSTON_ROCKETS,Location.HOME,Team.PHILADELPHIA_76ERS,Outcome.WIN,2449,13,24,6,...,12,12,1,10,11,1,1,5,3,39.3
2,simmobe01,Ben Simmons,Team.PHILADELPHIA_76ERS,Location.AWAY,Team.HOUSTON_ROCKETS,Outcome.LOSS,2532,13,20,0,...,3,7,6,7,11,3,4,3,5,33.4
3,capelca01,Clint Capela,Team.HOUSTON_ROCKETS,Location.HOME,Team.PHILADELPHIA_76ERS,Outcome.WIN,2214,12,16,0,...,6,8,3,11,3,2,1,0,4,31.4
4,lillada01,Damian Lillard,Team.PORTLAND_TRAIL_BLAZERS,Location.AWAY,Team.WASHINGTON_WIZARDS,Outcome.WIN,2056,10,20,2,...,13,14,0,3,3,1,0,1,1,27.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,harteis01,Isaiah Hartenstein,Team.HOUSTON_ROCKETS,Location.HOME,Team.PHILADELPHIA_76ERS,Outcome.WIN,666,0,2,0,...,0,0,0,2,1,0,0,0,2,-0.9
116,diallch01,Cheick Diallo,Team.PHOENIX_SUNS,Location.HOME,Team.NEW_YORK_KNICKS,Outcome.WIN,484,0,3,0,...,0,0,1,1,0,0,0,0,0,-1.1
117,schofad01,Admiral Schofield,Team.WASHINGTON_WIZARDS,Location.HOME,Team.PORTLAND_TRAIL_BLAZERS,Outcome.LOSS,742,0,3,0,...,1,2,0,2,0,0,0,0,2,-1.7
118,scottmi01,Mike Scott,Team.PHILADELPHIA_76ERS,Location.AWAY,Team.HOUSTON_ROCKETS,Outcome.LOSS,721,0,4,0,...,0,0,0,4,1,0,0,0,2,-1.7
119,herroty01,Tyler Herro,Team.MIAMI_HEAT,Location.AWAY,Team.ORLANDO_MAGIC,Outcome.LOSS,1483,2,11,0,...,0,1,1,4,1,1,0,2,1,-2.1

In [124]:
df = all_data(2020, 2, 1)

TypeError: append() missing 1 required positional argument: 'other'

In [143]:
df

Empty DataFrame
Columns: []
Index: []

In [119]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
westbrook_4years.to_csv('westbrook_2014_2019.csv')