## Building Tables for AWS RDS PostgresSQL

In [2]:
import psycopg2
import pandas as pd

In [3]:
connection = psycopg2.connect(
    host = 'project3.cdr354qikgy9.us-east-2.rds.amazonaws.com',
    port = 5431,
    user = 'NBA',
    password = 'NBAFun23!',
    database='NBA_predictor'
    )

#cursor object interacts and executes the commands on the Postgres database 
cursor=connection.cursor()

In [25]:
#check what is in the database
query = """SELECT * FROM pg_catalog.pg_tables
            WHERE schemaname != 'pg_catalog'
            AND schemaname != 'information_schema';"""
cursor.execute(query)
cursor.fetchall()

[]

## Creating Tables for Advanced Stats, Encoded Box Scores, All Usage

In [26]:
AdvancedStats_table  = """CREATE TABLE AdvStats(id integer, Player varchar(50), Pos varchar(5), Age numeric, Tm varchar(3), 
                        G numeric NULL, MP numeric NULL, PER float NULL, TSpct numeric NULL, ThreePAr numeric NULL, FTr numeric NULL,
                        ORBpct numeric NULL, DRBpct numeric NULL, TRBpct numeric NULL, ASTpct numeric NULL, STLpct numeric NULL, 
                        BLKpct numeric NULL, TOVpct numeric NULL, USGpct numeric NULL, OWS numeric NULL, DWS numeric NULL, 
                        WS numeric NULL, WS48 numeric NULL, OBPM numeric NULL, BPM numeric NULL, VORP numeric NULL, Year numeric, 
                        slug varchar(20));""";

cursor.execute(AdvancedStats_table);
#Commit table creation
connection.commit()

#### importing advanced stats .csv file to table

In [29]:
#inserting .csv files using copy_from() into table  
with open('../Resources/adv_stats_all_slug.csv', 'r', encoding="utf8") as row:
    # Skip the header row
    next(row)
    cursor.copy_from(row, 'AdvStats', sep=',')

InvalidTextRepresentation: invalid input syntax for type numeric: ""
CONTEXT:  COPY advstats, line 73, column tspct: ""

In [20]:
cursor.execute("""DROP TABLE """)
connection.commit()

In [21]:
Encoded_Box_ScoresTable =    """CREATE TABLE boxscore(id integer, slug varchar(20), name varchar(40), Team varchar(40), Location varchar(6),
                                Opponent varchar(40), Outcome varchar(5), seconds_played numeric, made_field_goals numeric, atempted_filed_goals numeric, 
                                made_three_point_fg numeric, att_three_point_fg numeric, made_free_throws numeric, attempted_free_throws numeric, 
                                offensive_rebounds numeric, defensive_rebounds numeric, assists numeric, steals numeric, blocks numeric, turnovers numeric,
                                personal_fouls numeric, game_score numeric, date date, game_id integer, spread integer);""";

cursor.execute(Encoded_Box_ScoresTable);
connection.commit()

In [22]:
#inserting .csv files using copy_from() into table  
with open('../Resources/encoded_box_scores.csv', 'r', encoding="utf8") as row:
    # Skip the header row
    next(row)
    cursor.copy_from(row, 'boxscore', sep=',')
connection.commit()

In [24]:
sql = """
SELECT * from boxscore
"""

pd.read_sql(sql, con=connection)

,id,slug,name,team,location,opponent,outcome,seconds_played,made_field_goals,atempted_filed_goals,...,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,game_score,date,game_id,spread
0,0,anthoca01,Carmelo Anthony,NEW_YORK_KNICKS,HOME,PORTLAND_TRAIL_BLAZERS,LOSS,2472.0,14.0,24.0,...,5.0,4.0,1.0,0.0,2.0,3.0,36.5,2013-01-01,459,5
1,1,smithjr01,J.R. Smith,NEW_YORK_KNICKS,HOME,PORTLAND_TRAIL_BLAZERS,LOSS,2413.0,10.0,22.0,...,8.0,5.0,3.0,0.0,2.0,2.0,24.0,2013-01-01,459,5
2,2,bryanko01,Kobe Bryant,LOS_ANGELES_LAKERS,HOME,PHILADELPHIA_76ERS,LOSS,2545.0,14.0,29.0,...,2.0,0.0,1.0,0.0,3.0,2.0,20.7,2013-01-01,462,4
3,3,anderry01,Ryan Anderson,NEW_ORLEANS_HORNETS,HOME,ATLANTA_HAWKS,LOSS,1928.0,9.0,15.0,...,3.0,0.0,0.0,0.0,0.0,2.0,18.3,2013-01-01,460,9
4,4,vasqugr01,Greivis Vásquez,NEW_ORLEANS_HORNETS,HOME,ATLANTA_HAWKS,LOSS,2317.0,7.0,15.0,...,8.0,10.0,0.0,1.0,2.0,1.0,16.9,2013-01-01,460,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200892,100377,netora01,Raul Neto,PHILADELPHIA_76ERS,AWAY,MILWAUKEE_BUCKS,LOSS,23.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-02-06,9958,11
200893,100378,smithzh01,Zhaire Smith,PHILADELPHIA_76ERS,AWAY,MILWAUKEE_BUCKS,LOSS,23.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-02-06,9958,11
200894,100379,belinma01,Marco Belinelli,SAN_ANTONIO_SPURS,AWAY,PORTLAND_TRAIL_BLAZERS,LOSS,166.0,0.0,2.0,...,1.0,1.0,0.0,0.0,0.0,0.0,-0.4,2020-02-06,9959,8
200895,100380,okafoja01,Jahlil Okafor,NEW_ORLEANS_PELICANS,AWAY,CHICAGO_BULLS,WIN,423.0,1.0,2.0,...,0.0,0.0,0.0,0.0,1.0,1.0,-0.4,2020-02-06,9957,6
200896,100381,alexani01,Nickeil Alexander-Walker,NEW_ORLEANS_PELICANS,AWAY,CHICAGO_BULLS,WIN,262.0,0.0,0.0,...,1.0,1.0,0.0,0.0,2.0,2.0,-1.8,2020-02-06,9957,6

In [ ]:
AllUsageTable = """CREATE TABLE allusage(season date, GP numeric, MIN numeric, USGper numeric, FGMper numeric, FGAper numeric, threePAper
                    FTMper numeric, FTAper numeric, OREBper numeric, DREBper numeric, REBper numeric, ASTper numeric, TOVper numeric,
                    STLper numeric, BLKper numeric, BLKAper numeric, PFper numeric, PFDper numeric, PTSper numeric, stats_id integer, 
                    player varchar(40);""");

cursor.execute(ALLUsageTable);
connection.commit()