## Player Advanced Stats by Year

In [1]:
import pandas as pd
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [4]:
def adv_stats (year):
    url = "https://www.basketball-reference.com/leagues/NBA_{}_advanced.html".format(year)
    html = urlopen(url)
    soup = BeautifulSoup(html)
    #use find_all from beautifulsoup to locate the header in the first table row (tag <tr>)
    tr_header = soup.find_all('tr')[0]
    #use get_text to extract column header names from table header (tag <th>) into a list
    headers = [th.get_text() for th in tr_header.find_all('th')]
    #drop first ranking column
    headers = headers[1:]
    #skip header row 
    tr_rows = soup.find_all('tr')[1:]
    #use get_text to extract player data from table data (tag <td>), skipping column header row
    player_data = [[td.get_text() for td in tr_rows[i].find_all('td')] for i in range(len(tr_rows))]
    #create dataframe of data and column header
    adv_stats_df = pd.DataFrame(player_data, columns=headers)
    
    return(adv_stats_df)

In [5]:
adv_stats(2019).head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP
0,Álex Abrines,SG,25,OKC,31,588,6.3,.507,.809,.083,...,,0.1,0.6,0.6,.053,,-2.4,-0.9,-3.4,-0.2
1,Quincy Acy,PF,28,PHO,10,123,2.9,.379,.833,.556,...,,-0.1,0.0,-0.1,-0.022,,-5.7,-0.3,-5.9,-0.1
2,Jaylen Adams,PG,22,ATL,34,428,7.6,.474,.673,.082,...,,-0.1,0.2,0.1,.011,,-3.1,-1.3,-4.4,-0.3
3,Steven Adams,C,25,OKC,80,2669,18.5,.591,.002,.361,...,,5.1,4.0,9.1,.163,,0.6,2.1,2.7,3.2
4,Bam Adebayo,C,21,MIA,82,1913,17.9,.623,.031,.465,...,,3.4,3.4,6.8,.171,,-0.6,3.6,3.0,2.4

In [6]:
adv_stats(2018).head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP
0,Álex Abrines,SG,24,OKC,75,1134,9.0,.567,.759,.158,...,,1.3,1.0,2.2,.094,,-0.5,-1.7,-2.2,-0.1
1,Quincy Acy,PF,27,BRK,70,1359,8.2,.525,.800,.164,...,,-0.1,1.1,1.0,.036,,-2.0,-0.2,-2.2,-0.1
2,Steven Adams,C,24,OKC,76,2487,20.6,.630,.003,.402,...,,6.7,3.0,9.7,.187,,2.2,1.1,3.3,3.3
3,Bam Adebayo,C,20,MIA,69,1368,15.7,.570,.021,.526,...,,2.3,1.9,4.2,.148,,-1.6,1.8,0.2,0.8
4,Arron Afflalo,SG,32,ORL,53,682,5.8,.516,.432,.160,...,,-0.1,0.2,0.1,.009,,-4.1,-1.8,-5.8,-0.7

In [7]:
adv_stats(2017).head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP
0,Álex Abrines,SG,23,OKC,68,1055,10.1,.560,.724,.144,...,,1.2,0.9,2.1,.096,,-0.3,-2.2,-2.5,-0.1
1,Quincy Acy,PF,26,TOT,38,558,11.8,.565,.529,.353,...,,0.5,0.5,0.9,.082,,-1.8,-1.2,-3.0,-0.1
2,Quincy Acy,PF,26,DAL,6,48,-1.4,.355,.412,.176,...,,-0.2,0.0,-0.1,-0.133,,-10.1,-6.0,-16.2,-0.2
3,Quincy Acy,PF,26,BRK,32,510,13.1,.587,.542,.373,...,,0.6,0.5,1.1,.102,,-1.1,-0.7,-1.8,0.0
4,Steven Adams,C,23,OKC,80,2389,16.5,.589,.002,.392,...,,3.3,3.1,6.5,.130,,-0.7,1.2,0.6,1.5

In [8]:
adv_stats(2016).head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP
0,Quincy Acy,PF,25,SAC,59,876,14.7,.629,.229,.318,...,,1.8,0.7,2.5,.137,,0.2,0.0,0.2,0.5
1,Jordan Adams,SG,21,MEM,2,15,17.3,.427,.167,.833,...,,0.0,0.0,0.0,.015,,-2.9,4.8,1.9,0.0
2,Steven Adams,C,22,OKC,80,2014,15.5,.621,.000,.460,...,,4.2,2.3,6.5,.155,,0.8,1.3,2.1,2.1
3,Arron Afflalo,SG,30,NYK,71,2371,10.9,.531,.298,.164,...,,1.8,0.9,2.7,.055,,-0.6,-1.8,-2.4,-0.2
4,Alexis Ajinça,C,27,NOP,59,861,13.8,.514,.003,.197,...,,0.2,0.9,1.0,.058,,-4.3,-0.2,-4.5,-0.5

In [9]:
adv_stats(2015).head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP
0,Quincy Acy,PF,24,NYK,68,1287,11.9,.533,.181,.293,...,,1.0,0.7,1.7,.063,,-2.3,-0.8,-3.1,-0.3
1,Jordan Adams,SG,20,MEM,30,248,12.8,.489,.291,.267,...,,0.0,0.4,0.4,.073,,-1.8,1.2,-0.6,0.1
2,Steven Adams,C,21,OKC,70,1771,14.1,.549,.005,.514,...,,1.9,2.2,4.1,.111,,-1.4,1.8,0.4,1.1
3,Jeff Adrien,PF,28,MIN,17,215,14.2,.494,.000,.864,...,,0.2,0.2,0.4,.087,,-2.7,0.5,-2.2,0.0
4,Arron Afflalo,SG,29,TOT,78,2502,10.7,.533,.377,.224,...,,1.6,1.0,2.6,.050,,-0.5,-1.3,-1.8,0.1

In [10]:
adv_stats(2014).head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP
0,Quincy Acy,SF,23,TOT,63,847,10.1,.520,.106,.376,...,,0.6,0.9,1.5,.086,,-2.5,1.4,-1.1,0.2
1,Quincy Acy,SF,23,TOR,7,61,17.2,.542,.357,.571,...,,0.1,0.1,0.2,.188,,0.5,3.7,4.1,0.1
2,Quincy Acy,SF,23,SAC,56,786,9.6,.518,.079,.354,...,,0.5,0.7,1.3,.078,,-2.8,1.2,-1.5,0.1
3,Steven Adams,C,20,OKC,81,1197,11.2,.541,.000,.735,...,,0.9,1.9,2.9,.114,,-2.1,2.4,0.3,0.7
4,Jeff Adrien,PF,27,TOT,53,961,17.4,.553,.000,.433,...,,1.6,1.1,2.7,.134,,-1.4,0.3,-1.1,0.2

In [11]:
adv_stats(2013).head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP
0,Quincy Acy,PF,22,TOR,29,342,15.9,.632,.027,.507,...,,0.7,0.4,1.1,.157,,-0.6,1.3,0.7,0.2
1,Jeff Adrien,PF,26,CHA,52,713,13.4,.493,.012,.595,...,,0.5,0.4,1.0,.064,,-3.0,-0.2,-3.3,-0.2
2,Arron Afflalo,SF,27,ORL,64,2307,13.0,.527,.265,.246,...,,1.5,0.5,2.0,.042,,-0.3,-2.0,-2.3,-0.2
3,Josh Akognon,PG,26,DAL,3,9,15.3,.625,.500,.000,...,,0.0,0.0,0.0,.196,,4.7,-4.9,-0.2,0.0
4,Cole Aldrich,C,24,TOT,45,388,11.1,.563,.000,.250,...,,0.1,0.4,0.6,.070,,-4.8,0.7,-4.0,-0.2

In [12]:
adv_stats(2012).head()

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP
0,Jeff Adrien,PF,25,HOU,8,63,11.2,.493,.000,.750,...,,0.1,0.1,0.1,.106,,-5.4,-2.3,-7.7,-0.1
1,Arron Afflalo,SG,26,DEN,62,2086,14.7,.584,.316,.353,...,,4.7,0.6,5.3,.121,,2.5,-1.6,0.8,1.5
2,Blake Ahearn,PG,27,UTA,4,30,-7.3,.357,.643,.000,...,,-0.2,0.0,-0.2,-0.315,,-10.3,-6.0,-16.3,-0.1
3,Solomon Alabi,C,23,TOR,14,122,14.2,.418,.000,.222,...,,0.0,0.2,0.2,.083,,-5.6,1.5,-4.1,-0.1
4,Cole Aldrich,C,23,OKC,26,173,17.7,.592,.000,.333,...,,0.3,0.4,0.6,.176,,-2.4,2.7,0.3,0.1

In [33]:
def adv_stats_all():
    
    year = [2013, 2014, 2015, 2016, 2017, 2018, 2019]
    adv_stats_df_all = pd.DataFrame()
    
    for year in year:
        url = "https://www.basketball-reference.com/leagues/NBA_{}_advanced.html".format(year)
        html = urlopen(url)
        soup = BeautifulSoup(html)
        #use find_all from beautifulsoup to locate the header in the first table row (tag <tr>)
        tr_header = soup.find_all('tr')[0]
        #use get_text to extract column header names from table header (tag <th>) into a list
        headers = [th.get_text() for th in tr_header.find_all('th')]
        #drop first ranking column
        headers = headers[1:]
        #skip header row 
        tr_rows = soup.find_all('tr')[1:]
        #use get_text to extract player data from table data (tag <td>), skipping column header row
        player_data = [[td.get_text() for td in tr_rows[i].find_all('td')] for i in range(len(tr_rows))]
        #create dataframe of data and column header
        adv_stats_df = pd.DataFrame(player_data, columns=headers)
        adv_stats_df['Year']= year
        adv_stats_df_all = adv_stats_df_all.append(adv_stats_df)
    
    return(adv_stats_df_all)

In [35]:
adv_stats_all_df = adv_stats_all()
adv_stats_all_df

,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,FTr,...,OWS,DWS,WS,WS/48,,OBPM,DBPM,BPM,VORP,Year
0,Quincy Acy,PF,22,TOR,29,342,15.9,.632,.027,.507,...,0.7,0.4,1.1,.157,,-0.6,1.3,0.7,0.2,2013
1,Jeff Adrien,PF,26,CHA,52,713,13.4,.493,.012,.595,...,0.5,0.4,1.0,.064,,-3.0,-0.2,-3.3,-0.2,2013
2,Arron Afflalo,SF,27,ORL,64,2307,13.0,.527,.265,.246,...,1.5,0.5,2.0,.042,,-0.3,-2.0,-2.3,-0.2,2013
3,Josh Akognon,PG,26,DAL,3,9,15.3,.625,.500,.000,...,0.0,0.0,0.0,.196,,4.7,-4.9,-0.2,0.0,2013
4,Cole Aldrich,C,24,TOT,45,388,11.1,.563,.000,.250,...,0.1,0.4,0.6,.070,,-4.8,0.7,-4.0,-0.2,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
729,Tyler Zeller,C,29,MEM,4,82,19.4,.640,.000,.643,...,0.2,0.1,0.3,.191,,-0.3,-1.3,-1.5,0.0,2019
730,Ante Žižić,C,22,CLE,59,1082,16.2,.590,.000,.399,...,1.7,0.3,2.0,.087,,-1.7,-1.4,-3.1,-0.3,2019
731,Ivica Zubac,C,21,TOT,59,1040,18.9,.604,.000,.332,...,1.9,1.3,3.2,.148,,-1.2,1.0,-0.3,0.5,2019
732,Ivica Zubac,C,21,LAL,33,516,19.5,.633,.000,.342,...,1.1,0.6,1.8,.165,,-1.3,0.4,-0.9,0.1,2019
733,Ivica Zubac,C,21,LAC,26,524,18.3,.574,.000,.323,...,0.7,0.7,1.4,.132,,-1.2,1.5,0.3,0.3,2019