## Reference Lineup

In [1]:
import pandas as pd
from urllib.request import urlopen
from bs4 import BeautifulSoup
import sys 
sys.path.append('../Scripts')
import starting_lineup_functions as slp

../Scripts\starting_lineup_functions.py:11: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  PLAYER_DICT = players.T.to_dict('list')

In [43]:
team_names = slp.PAST_DICT
team_name_list = []

for values in team_names.values():
    team_name_list += values

In [45]:
team_name_list.remove('CHB')

In [62]:
team_name_list

['ATL',
 'BKN',
 'BOS',
 'CHA',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MEM',
 'MIA',
 'MIL',
 'MIN',
 'NOP',
 'NOP',
 'NYK',
 'OKC',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'TOR',
 'UTA',
 'WAS']

In [132]:
def starting_lineup_test(team, year):
    
    url = 'https://www.basketball-reference.com/teams/{}/{}_start.html'.format(team, year)
    html = urlopen(url)
    soup = BeautifulSoup(html)
    tr_rows = soup.find_all('tr')[1:83]
    lineup_data = [[a.get_text() for a in tr_rows[i].find_all('a')] for i in range(len(tr_rows))]
    header = ['Game Date', 'Box Score', 'Team', 'Player1', 'Player2', 'Player3', 'Player4', 'Player5']
    lineup_data_df = pd.DataFrame(lineup_data, columns=header)
    lineup_data_df['Team'] = team 
    lineup_data_df['Game Date'] = pd.to_datetime(lineup_data_df['Game Date'])
    
    return lineup_data_df

In [186]:
#starting_lineup_test('BKN',2013)
#missing BKN and 2013 data due to NOP name change

In [184]:
def starting_lineup():
        
    team_name_list = ['ATL','BOS','BRK', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA',
                       'MIL', 'MIN', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHO', 'POR', 'SAC', 'SAS', 'TOR', 'UTA', 'WAS']
    header = ['Game Date', 'Box Score', 'Team', 'Player1', 'Player2', 'Player3', 'Player4', 'Player5']
    lineup_data_final = pd.DataFrame()
    year = [2014, 2015, 2016, 2017, 2018, 2019]
    
    for i in team_name_list:
        for j in year:  
            url = 'https://www.basketball-reference.com/teams/{}/{}_start.html'.format(i, j)
            html = urlopen(url)
            soup = BeautifulSoup(html)
            tr_rows = soup.find_all('tr')[1:83]
            lineup_data = [[a.get_text() for a in tr_rows[i].find_all('a')] for i in range(len(tr_rows))]
            lineup_data_df = pd.DataFrame(lineup_data, columns=header)
            lineup_data_df['Team'] = i 
            lineup_data_df['Game Date'] = pd.to_datetime(lineup_data_df['Game Date'])
            lineup_data_final = lineup_data_final.append(lineup_data_df)
    
    
    return lineup_data_final

In [185]:
starting_lineup_final = starting_lineup()
starting_lineup_final

,Game Date,Box Score,Team,Player1,Player2,Player3,Player4,Player5
0,2013-10-30,Box Score,ATL,D. Carroll,A. Horford,K. Korver,P. Millsap,J. Teague
1,2013-11-01,Box Score,ATL,D. Carroll,A. Horford,K. Korver,P. Millsap,J. Teague
2,2013-11-03,Box Score,ATL,D. Carroll,A. Horford,K. Korver,P. Millsap,J. Teague
3,2013-11-05,Box Score,ATL,D. Carroll,A. Horford,K. Korver,P. Millsap,J. Teague
4,2013-11-07,Box Score,ATL,D. Carroll,A. Horford,K. Korver,P. Millsap,J. Teague
...,...,...,...,...,...,...,...,...
77,2019-03-31,Box Score,WAS,B. Beal,T. Brown,T. Bryant,B. Portis,T. Satoranský
78,2019-04-03,Box Score,WAS,B. Beal,T. Brown,T. Bryant,B. Portis,T. Satoranský
79,2019-04-05,Box Score,WAS,B. Beal,T. Brown,T. Bryant,B. Portis,T. Satoranský
80,2019-04-07,Box Score,WAS,B. Beal,T. Brown,T. Bryant,B. Portis,T. Satoranský
81,2019-04-09,Box Score,WAS,B. Beal,T. Brown,T. Bryant,B. Portis,T. Satoranský

In [187]:
starting_lineup_final.to_csv('../Resources/starting_lineup.csv')